version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
    - npm run export
  post_build:
    commands:
      - echo "s3://${ARTIFACTS_BUCKET}/"
      - aws s3 rm --recursive "s3://${ARTIFACTS_BUCKET}/"
artifacts:
  files:
  - '**/*'
  base-directory: out
  name: ReactBuildArtifact